language: python
install:
  - pip install coveralls
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
- GLUE_PLATE_BASE_MODULE=basepackage.basepackage_settings BASEPACKAGE_SETTINGS_MODULE=subpackage.basepackage_subpackage_settings
script: cd tests && PYTHONPATH=..:$PYTHONPATH coverage run --source=glueplate test_doctest.py
after_success:
  - coveralls
